<div class="footer">
            <h3>CONTACT ME!</h3>
            <div class="row">
                <div class="column">
                    <a href="https://www.linkedin.com/in/adeel-qayum/" target="_blank"><img src="images/linkedinlogo.png" alt="LinkedIn"></a>
                </div>
                <div class="column">
                    <a href="https://github.com/adeelqayum" target="_blank"><img src="images/githublogo.png" alt="Github"></a>
                </div>
                <div class="column">
                    <a href="mailto:aqayum97@gmail.com" target="_blank"><img src="images/maillogo.png" alt="E-Mail"></a>
                </div>
            </div>
        </div>