        <header>
        <a href="index.php"><img src="images/logofullname.png"></a>
            <nav>
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="about.php">About Me</a></li>
                    <li><a href="https://drive.google.com/file/d/1FEc-lnnSEZVCiYWy_LVlX9dMZdjdEWfI/view?usp=sharing" target="_blank">Resume</a></li>
                </ul>
            </nav>
            
        </header>